_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.6
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
batch_size:
    value: 100
dropout_rate:
    value: 0.2
early_stop_patience:
    value: 50
epochs:
    value: 1000
fno_channels:
    value: 1
fno_modes:
    value: 100
fno_width:
    value: 64
input_size:
    value: 29
latent_dim:
    value: 100
learning_rate:
    value: 0.005
optimizer:
    value: Adam
output_size:
    value: 200
