_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.6
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
batch_size:
    value: 50
epochs:
    value: 100
input_size:
    value: 30
latent_dim:
    value: 64
learning_rate:
    value: 0.001
optimizer:
    value: Adam
output_size:
    value: 1000
